# Generated by Django 4.0.1 on 2022-03-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imges',
            new_name='image',
        ),
    ]
