# Generated by Django 4.0.1 on 2022-05-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_testresult_passed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-create_time']},
        ),
    ]
