# Generated by Django 4.0.1 on 2022-06-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskcaserelevance_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcaserelevance',
            name='case',
            field=models.TextField(default='', null=True, verbose_name='管理用例'),
        ),
    ]
