# Generated by Django 4.0.1 on 2022-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='名称'),
        ),
    ]
