# Generated by Django 4.0.1 on 2022-07-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_testextract'),
    ]

    operations = [
        migrations.AddField(
            model_name='testextract',
            name='extract',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='提取规则'),
        ),
        migrations.AlterField(
            model_name='testextract',
            name='value',
            field=models.CharField(blank=True, default='{}', max_length=1000, null=True, verbose_name='提取值'),
        ),
    ]
