# Generated by Django 4.0.1 on 2022-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_testextract_extract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testextract',
            name='case',
        ),
        migrations.AddField(
            model_name='testextract',
            name='case_id',
            field=models.IntegerField(default=0, verbose_name='用例 id'),
        ),
    ]
