# Generated by Django 4.0.1 on 2022-07-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_testextract_case_testextract_case_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='module',
            new_name='module_id',
        ),
    ]
