# Generated by Django 4.0.1 on 2022-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_rename_module_testcase_module_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='module_id',
            new_name='module',
        ),
    ]
